// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuLMfBjz8cmvD9_ciHP4IIZ7OgSCzHTTs',
    appId: '1:611717375598:web:27f2c5953b15a35a4de87f',
    messagingSenderId: '611717375598',
    projectId: 'naihydro',
    authDomain: 'naihydro.firebaseapp.com',
    storageBucket: 'naihydro.firebasestorage.app',
    measurementId: 'G-43FNW8KRZ4',
    databaseURL: 'https://naihydro-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM0Qw4lqCuEoKYuuTiMCnLubddwwxsOnI',
    appId: '1:611717375598:android:4b6fa66f9b83d4a64de87f',
    messagingSenderId: '611717375598',
    projectId: 'naihydro',
    storageBucket: 'naihydro.firebasestorage.app',
    databaseURL: 'https://naihydro-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGfqITahZ0eGYKw8xSz5Rsi6cJwm9IHNY',
    appId: '1:611717375598:ios:9f1205c98499929e4de87f',
    messagingSenderId: '611717375598',
    projectId: 'naihydro',
    storageBucket: 'naihydro.firebasestorage.app',
    iosBundleId: 'com.example.naihydro',
    databaseURL: 'https://naihydro-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGfqITahZ0eGYKw8xSz5Rsi6cJwm9IHNY',
    appId: '1:611717375598:ios:9f1205c98499929e4de87f',
    messagingSenderId: '611717375598',
    projectId: 'naihydro',
    storageBucket: 'naihydro.firebasestorage.app',
    iosBundleId: 'com.example.naihydro',
    databaseURL: 'https://naihydro-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuLMfBjz8cmvD9_ciHP4IIZ7OgSCzHTTs',
    appId: '1:611717375598:web:2afbd53debd2b6f14de87f',
    messagingSenderId: '611717375598',
    projectId: 'naihydro',
    authDomain: 'naihydro.firebaseapp.com',
    storageBucket: 'naihydro.firebasestorage.app',
    measurementId: 'G-GC1XV2V71D',
    databaseURL: 'https://naihydro-default-rtdb.europe-west1.firebasedatabase.app/',
  );
}
